CREATE TABLE IF NOT EXISTS provider_key_quota_observations (
    provider_api_key_id VARCHAR(191) NOT NULL,
    provider_id VARCHAR(191) NOT NULL,
    provider_api_key_name VARCHAR(512) NOT NULL,
    provider_type VARCHAR(128) NOT NULL,
    bucket_start_unix_secs BIGINT UNSIGNED NOT NULL,
    observed_at_unix_secs BIGINT UNSIGNED NOT NULL,
    source VARCHAR(128) NOT NULL,
    plan_type VARCHAR(191) NULL,
    status_code VARCHAR(191) NULL,
    status_label VARCHAR(512) NULL,
    freshness VARCHAR(64) NULL,
    credits_balance DOUBLE NULL,
    credits_unlimited BOOLEAN NULL,
    reset_credits_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (provider_api_key_id, bucket_start_unix_secs),
    KEY idx_provider_key_quota_observations_provider_time (provider_id, observed_at_unix_secs DESC),
    KEY idx_provider_key_quota_observations_key_time (provider_api_key_id, observed_at_unix_secs DESC)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS provider_key_quota_window_observations (
    provider_api_key_id VARCHAR(191) NOT NULL,
    bucket_start_unix_secs BIGINT UNSIGNED NOT NULL,
    window_identity VARCHAR(512) NOT NULL,
    code VARCHAR(191) NOT NULL,
    label VARCHAR(512) NOT NULL,
    scope VARCHAR(191) NULL,
    model VARCHAR(512) NULL,
    unit VARCHAR(128) NULL,
    used_percent DOUBLE NULL,
    remaining_percent DOUBLE NULL,
    used_value DOUBLE NULL,
    remaining_value DOUBLE NULL,
    limit_value DOUBLE NULL,
    reset_at_unix_secs BIGINT UNSIGNED NULL,
    window_minutes BIGINT UNSIGNED NULL,
    exhausted BOOLEAN NOT NULL DEFAULT FALSE,
    local_request_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    local_total_tokens BIGINT UNSIGNED NOT NULL DEFAULT 0,
    local_cost_usd DOUBLE NOT NULL DEFAULT 0,
    PRIMARY KEY (provider_api_key_id, bucket_start_unix_secs, window_identity),
    KEY idx_provider_key_quota_windows_key_time (provider_api_key_id, bucket_start_unix_secs DESC)
) ENGINE=InnoDB;
